#include <rainbow/water_refractive_index.hpp>
#include <array>
#include <cmath>
#include <iostream>
#include <limits>
#include <stdexcept>

namespace
{
unsigned checks=0;
void require(bool b, const char* m){++checks;if(!b)throw std::runtime_error(m);}
template<class F> void rejects(F f)
{
    bool caught=false;try{f();}catch(const std::exception&){caught=true;}
    require(caught,"Invalid/out-of-contract material input was accepted.");
}
}
int main()
{
    try
    {
        // Published verification values, NOT values generated by the implementation.
        // IAPWS R9-97 Table 3: 0 Celsius, absolute refractive index.
        constexpr std::array<double,4> pressures{{1e5,1e6,1e7,1e8}};
        struct Verification {double wavelength;std::array<double,4> expected;};
        constexpr std::array<Verification,3> rows{{
            {226.50,{{1.394527,1.394711,1.396526,1.412733}}},
            {589.00,{{1.334344,1.334494,1.335969,1.349101}}},
            {1013.98,{{1.326135,1.326279,1.327710,1.340435}}}
        }};
        for(const auto& row:rows)for(unsigned j=0;j<pressures.size();++j)
        {
            const auto s=rainbow::evaluate_water_optics(row.wavelength,0,pressures[j]);
            require(std::abs(s.refractive_index-row.expected[j])<=1e-6,
                "R9-97 Table 3 refractive index mismatch.");
            require(std::abs(s.density_pressure_residual_pascal)<=0.02,"Pressure residual exceeded contract.");
            require(s.density_bracket_width_kg_m3<=2e-10,"Density bracket is too wide.");
        }
        // R6-95(2018), Table 7. Invert two tabulated pressure values at T=300 K.
        // The published p and rho are rounded; compare within their precision.
        const auto a=rainbow::evaluate_water_optics(589,26.85,0.992418352e-1*1e6);
        const auto b=rainbow::evaluate_water_optics(589,26.85,0.200022515e2*1e6);
        require(std::abs(a.density_kg_m3-996.5560)<2e-6,"R6-95 Table 7 low-pressure mismatch.");
        require(std::abs(b.density_kg_m3-1005.308)<2e-6,"R6-95 Table 7 high-pressure mismatch.");
        // Application-domain sweep: finite nonabsorbing dispersion, a single
        // thermodynamic state across wavelengths, and T/P not tied to grid sizes.
        for(double T:{0.0,10.0,20.0,40.0,60.0})for(double p:{5e4,101325.0,1e6,1e7,1e8})
        {
            double previous=std::numeric_limits<double>::infinity();
            const auto reference=rainbow::evaluate_water_optics(589,T,p);
            for(int wavelength=200;wavelength<=1100;wavelength+=25)
            {
                const auto s=rainbow::evaluate_water_optics(double(wavelength),T,p);
                require(std::isfinite(s.refractive_index) && s.refractive_index>1.0,"Bad liquid index.");
                require(s.refractive_index<previous,"Unexpected dispersion ordering in application domain.");
                require(s.density_kg_m3==reference.density_kg_m3,"Density depends on wavelength.");
                require(std::abs(s.density_pressure_residual_pascal)<=0.02,"Sweep density residual.");
                previous=s.refractive_index;
            }
        }
        const auto n0=rainbow::evaluate_water_optics(700);
        require(std::abs(n0.refractive_index-1.33051928291405)<2e-12,"20C reference changed.");
        require(rainbow::water_refractive_index_r9_97(589,293.15,0)==1.0,"Vacuum density limit.");
        const double nan=std::numeric_limits<double>::quiet_NaN();
        for(double wavelength:{-1.0,0.0,199.0,1101.0,nan,std::numeric_limits<double>::infinity()})
            rejects([&]{(void)rainbow::evaluate_water_optics(wavelength);});
        for(double T:{-0.01,60.01,nan})rejects([&]{(void)rainbow::evaluate_water_optics(550,T);});
        for(double p:{0.0,49999.0,100000001.0,nan})rejects([&]{(void)rainbow::evaluate_water_optics(550,20,p);});
        for(double rho:{-1.0,1060.01,nan})rejects([&]{(void)rainbow::water_refractive_index_r9_97(550,293.15,rho);});
        for(double T:{261.14,773.16,nan})rejects([&]{(void)rainbow::water_refractive_index_r9_97(550,T,998);});
        std::cout<<"Water optical material: "<<checks<<" checks passed.\n";
        return 0;
    }
    catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}
}
