# CMake generated Testfile for 
# Source directory: C:/Users/sy415/workspace/rainbow/tests
# Build directory: C:/Users/sy415/workspace/rainbow/build-verify/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_field_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_field_cpu_tests.exe")
  set_tests_properties([=[rainbow_field_cpu]=] PROPERTIES  LABELS "cpu;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;63;add_test;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_field_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_field_cpu_tests.exe")
  set_tests_properties([=[rainbow_field_cpu]=] PROPERTIES  LABELS "cpu;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;63;add_test;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_field_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_field_cpu_tests.exe")
  set_tests_properties([=[rainbow_field_cpu]=] PROPERTIES  LABELS "cpu;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;63;add_test;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_field_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_field_cpu_tests.exe")
  set_tests_properties([=[rainbow_field_cpu]=] PROPERTIES  LABELS "cpu;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;63;add_test;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_field_cpu]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_field_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_field_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/tests/rainbow_field_test_module.dir/Debug/field_test_kernel.fatbin")
  set_tests_properties([=[rainbow_field_cuda]=] PROPERTIES  LABELS "gpu;cuda;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;65;add_test;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_field_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_field_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/tests/rainbow_field_test_module.dir/Release/field_test_kernel.fatbin")
  set_tests_properties([=[rainbow_field_cuda]=] PROPERTIES  LABELS "gpu;cuda;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;65;add_test;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_field_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_field_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/tests/rainbow_field_test_module.dir/MinSizeRel/field_test_kernel.fatbin")
  set_tests_properties([=[rainbow_field_cuda]=] PROPERTIES  LABELS "gpu;cuda;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;65;add_test;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_field_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_field_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/tests/rainbow_field_test_module.dir/RelWithDebInfo/field_test_kernel.fatbin")
  set_tests_properties([=[rainbow_field_cuda]=] PROPERTIES  LABELS "gpu;cuda;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;65;add_test;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_field_cuda]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_phase_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_phase_cpu_tests.exe")
  set_tests_properties([=[rainbow_phase_cpu]=] PROPERTIES  LABELS "cpu;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;63;add_test;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_phase_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_phase_cpu_tests.exe")
  set_tests_properties([=[rainbow_phase_cpu]=] PROPERTIES  LABELS "cpu;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;63;add_test;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_phase_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_phase_cpu_tests.exe")
  set_tests_properties([=[rainbow_phase_cpu]=] PROPERTIES  LABELS "cpu;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;63;add_test;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_phase_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_phase_cpu_tests.exe")
  set_tests_properties([=[rainbow_phase_cpu]=] PROPERTIES  LABELS "cpu;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;63;add_test;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_phase_cpu]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_phase_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_phase_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/tests/rainbow_phase_test_module.dir/Debug/phase_test_kernel.fatbin")
  set_tests_properties([=[rainbow_phase_cuda]=] PROPERTIES  LABELS "gpu;cuda;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;65;add_test;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_phase_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_phase_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/tests/rainbow_phase_test_module.dir/Release/phase_test_kernel.fatbin")
  set_tests_properties([=[rainbow_phase_cuda]=] PROPERTIES  LABELS "gpu;cuda;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;65;add_test;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_phase_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_phase_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/tests/rainbow_phase_test_module.dir/MinSizeRel/phase_test_kernel.fatbin")
  set_tests_properties([=[rainbow_phase_cuda]=] PROPERTIES  LABELS "gpu;cuda;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;65;add_test;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_phase_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_phase_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/tests/rainbow_phase_test_module.dir/RelWithDebInfo/phase_test_kernel.fatbin")
  set_tests_properties([=[rainbow_phase_cuda]=] PROPERTIES  LABELS "gpu;cuda;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;65;add_test;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_phase_cuda]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_raindrop_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_raindrop_cpu_tests.exe")
  set_tests_properties([=[rainbow_raindrop_cpu]=] PROPERTIES  LABELS "cpu;raindrop;physics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/raindrop_trace_tests.cmake;17;add_test;C:/Users/sy415/workspace/rainbow/tests/raindrop_trace_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;73;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_raindrop_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_raindrop_cpu_tests.exe")
  set_tests_properties([=[rainbow_raindrop_cpu]=] PROPERTIES  LABELS "cpu;raindrop;physics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/raindrop_trace_tests.cmake;17;add_test;C:/Users/sy415/workspace/rainbow/tests/raindrop_trace_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;73;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_raindrop_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_raindrop_cpu_tests.exe")
  set_tests_properties([=[rainbow_raindrop_cpu]=] PROPERTIES  LABELS "cpu;raindrop;physics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/raindrop_trace_tests.cmake;17;add_test;C:/Users/sy415/workspace/rainbow/tests/raindrop_trace_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;73;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_raindrop_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_raindrop_cpu_tests.exe")
  set_tests_properties([=[rainbow_raindrop_cpu]=] PROPERTIES  LABELS "cpu;raindrop;physics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/raindrop_trace_tests.cmake;17;add_test;C:/Users/sy415/workspace/rainbow/tests/raindrop_trace_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;73;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_raindrop_cpu]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_raindrop_optix]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_raindrop_optix_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_raindrop_trace_module.dir/Debug/raindrop_trace.optixir")
  set_tests_properties([=[rainbow_raindrop_optix]=] PROPERTIES  LABELS "gpu;optix;raindrop;physics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/raindrop_trace_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/raindrop_trace_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;73;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_raindrop_optix]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_raindrop_optix_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_raindrop_trace_module.dir/Release/raindrop_trace.optixir")
  set_tests_properties([=[rainbow_raindrop_optix]=] PROPERTIES  LABELS "gpu;optix;raindrop;physics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/raindrop_trace_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/raindrop_trace_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;73;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_raindrop_optix]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_raindrop_optix_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_raindrop_trace_module.dir/MinSizeRel/raindrop_trace.optixir")
  set_tests_properties([=[rainbow_raindrop_optix]=] PROPERTIES  LABELS "gpu;optix;raindrop;physics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/raindrop_trace_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/raindrop_trace_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;73;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_raindrop_optix]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_raindrop_optix_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_raindrop_trace_module.dir/RelWithDebInfo/raindrop_trace.optixir")
  set_tests_properties([=[rainbow_raindrop_optix]=] PROPERTIES  LABELS "gpu;optix;raindrop;physics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/raindrop_trace_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/raindrop_trace_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;73;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_raindrop_optix]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_patch_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_patch_cpu_tests.exe")
  set_tests_properties([=[rainbow_patch_cpu]=] PROPERTIES  LABELS "cpu;patch;geometry" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_build_tests.cmake;17;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_build_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;74;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_patch_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_patch_cpu_tests.exe")
  set_tests_properties([=[rainbow_patch_cpu]=] PROPERTIES  LABELS "cpu;patch;geometry" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_build_tests.cmake;17;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_build_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;74;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_patch_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_patch_cpu_tests.exe")
  set_tests_properties([=[rainbow_patch_cpu]=] PROPERTIES  LABELS "cpu;patch;geometry" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_build_tests.cmake;17;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_build_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;74;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_patch_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_patch_cpu_tests.exe")
  set_tests_properties([=[rainbow_patch_cpu]=] PROPERTIES  LABELS "cpu;patch;geometry" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_build_tests.cmake;17;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_build_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;74;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_patch_cpu]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_patch_optix]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_patch_optix_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/Debug/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_raindrop_trace_module.dir/Debug/raindrop_trace.optixir")
  set_tests_properties([=[rainbow_patch_optix]=] PROPERTIES  LABELS "gpu;cuda;optix;patch;geometry" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_build_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_build_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;74;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_patch_optix]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_patch_optix_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/Release/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_raindrop_trace_module.dir/Release/raindrop_trace.optixir")
  set_tests_properties([=[rainbow_patch_optix]=] PROPERTIES  LABELS "gpu;cuda;optix;patch;geometry" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_build_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_build_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;74;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_patch_optix]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_patch_optix_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/MinSizeRel/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_raindrop_trace_module.dir/MinSizeRel/raindrop_trace.optixir")
  set_tests_properties([=[rainbow_patch_optix]=] PROPERTIES  LABELS "gpu;cuda;optix;patch;geometry" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_build_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_build_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;74;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_patch_optix]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_patch_optix_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/RelWithDebInfo/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_raindrop_trace_module.dir/RelWithDebInfo/raindrop_trace.optixir")
  set_tests_properties([=[rainbow_patch_optix]=] PROPERTIES  LABELS "gpu;cuda;optix;patch;geometry" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_build_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_build_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;74;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_patch_optix]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_patch_query_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_patch_query_cpu_tests.exe")
  set_tests_properties([=[rainbow_patch_query_cpu]=] PROPERTIES  LABELS "cpu;patch;query;geometry" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_query_tests.cmake;15;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_query_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;75;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_patch_query_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_patch_query_cpu_tests.exe")
  set_tests_properties([=[rainbow_patch_query_cpu]=] PROPERTIES  LABELS "cpu;patch;query;geometry" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_query_tests.cmake;15;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_query_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;75;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_patch_query_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_patch_query_cpu_tests.exe")
  set_tests_properties([=[rainbow_patch_query_cpu]=] PROPERTIES  LABELS "cpu;patch;query;geometry" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_query_tests.cmake;15;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_query_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;75;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_patch_query_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_patch_query_cpu_tests.exe")
  set_tests_properties([=[rainbow_patch_query_cpu]=] PROPERTIES  LABELS "cpu;patch;query;geometry" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_query_tests.cmake;15;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_query_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;75;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_patch_query_cpu]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_patch_query_optix]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_patch_query_optix_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/Debug/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/Debug/patch_query.optixir")
  set_tests_properties([=[rainbow_patch_query_optix]=] PROPERTIES  LABELS "gpu;optix;patch;query;geometry" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_query_tests.cmake;16;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_query_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;75;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_patch_query_optix]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_patch_query_optix_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/Release/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/Release/patch_query.optixir")
  set_tests_properties([=[rainbow_patch_query_optix]=] PROPERTIES  LABELS "gpu;optix;patch;query;geometry" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_query_tests.cmake;16;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_query_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;75;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_patch_query_optix]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_patch_query_optix_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/MinSizeRel/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/MinSizeRel/patch_query.optixir")
  set_tests_properties([=[rainbow_patch_query_optix]=] PROPERTIES  LABELS "gpu;optix;patch;query;geometry" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_query_tests.cmake;16;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_query_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;75;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_patch_query_optix]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_patch_query_optix_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/RelWithDebInfo/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/RelWithDebInfo/patch_query.optixir")
  set_tests_properties([=[rainbow_patch_query_optix]=] PROPERTIES  LABELS "gpu;optix;patch;query;geometry" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_query_tests.cmake;16;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_query_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;75;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_patch_query_optix]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_optical_interpolation_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_optical_interpolation_cpu_tests.exe")
  set_tests_properties([=[rainbow_optical_interpolation_cpu]=] PROPERTIES  LABELS "cpu;numerics;optics;interpolation" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/optical_interpolation_tests.cmake;31;add_test;C:/Users/sy415/workspace/rainbow/tests/optical_interpolation_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;76;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_optical_interpolation_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_optical_interpolation_cpu_tests.exe")
  set_tests_properties([=[rainbow_optical_interpolation_cpu]=] PROPERTIES  LABELS "cpu;numerics;optics;interpolation" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/optical_interpolation_tests.cmake;31;add_test;C:/Users/sy415/workspace/rainbow/tests/optical_interpolation_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;76;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_optical_interpolation_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_optical_interpolation_cpu_tests.exe")
  set_tests_properties([=[rainbow_optical_interpolation_cpu]=] PROPERTIES  LABELS "cpu;numerics;optics;interpolation" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/optical_interpolation_tests.cmake;31;add_test;C:/Users/sy415/workspace/rainbow/tests/optical_interpolation_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;76;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_optical_interpolation_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_optical_interpolation_cpu_tests.exe")
  set_tests_properties([=[rainbow_optical_interpolation_cpu]=] PROPERTIES  LABELS "cpu;numerics;optics;interpolation" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/optical_interpolation_tests.cmake;31;add_test;C:/Users/sy415/workspace/rainbow/tests/optical_interpolation_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;76;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_optical_interpolation_cpu]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_patch_optics_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_patch_optics_cpu_tests.exe")
  set_tests_properties([=[rainbow_patch_optics_cpu]=] PROPERTIES  LABELS "cpu;optics;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_optics_tests.cmake;16;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_optics_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;77;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_patch_optics_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_patch_optics_cpu_tests.exe")
  set_tests_properties([=[rainbow_patch_optics_cpu]=] PROPERTIES  LABELS "cpu;optics;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_optics_tests.cmake;16;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_optics_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;77;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_patch_optics_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_patch_optics_cpu_tests.exe")
  set_tests_properties([=[rainbow_patch_optics_cpu]=] PROPERTIES  LABELS "cpu;optics;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_optics_tests.cmake;16;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_optics_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;77;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_patch_optics_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_patch_optics_cpu_tests.exe")
  set_tests_properties([=[rainbow_patch_optics_cpu]=] PROPERTIES  LABELS "cpu;optics;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_optics_tests.cmake;16;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_optics_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;77;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_patch_optics_cpu]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_patch_optics_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_patch_optics_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/Debug/patch_optics.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/Debug/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/Debug/patch_query.optixir")
  set_tests_properties([=[rainbow_patch_optics_cuda]=] PROPERTIES  LABELS "gpu;cuda;optix;optics;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_optics_tests.cmake;17;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_optics_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;77;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_patch_optics_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_patch_optics_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/Release/patch_optics.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/Release/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/Release/patch_query.optixir")
  set_tests_properties([=[rainbow_patch_optics_cuda]=] PROPERTIES  LABELS "gpu;cuda;optix;optics;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_optics_tests.cmake;17;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_optics_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;77;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_patch_optics_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_patch_optics_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/MinSizeRel/patch_optics.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/MinSizeRel/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/MinSizeRel/patch_query.optixir")
  set_tests_properties([=[rainbow_patch_optics_cuda]=] PROPERTIES  LABELS "gpu;cuda;optix;optics;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_optics_tests.cmake;17;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_optics_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;77;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_patch_optics_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_patch_optics_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/RelWithDebInfo/patch_optics.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/RelWithDebInfo/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/RelWithDebInfo/patch_query.optixir")
  set_tests_properties([=[rainbow_patch_optics_cuda]=] PROPERTIES  LABELS "gpu;cuda;optix;optics;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_optics_tests.cmake;17;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_optics_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;77;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_patch_optics_cuda]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_wave_optics_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_wave_optics_cpu_tests.exe")
  set_tests_properties([=[rainbow_wave_optics_cpu]=] PROPERTIES  LABELS "cpu;optics;focal;diffraction" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/wave_optics_tests.cmake;17;add_test;C:/Users/sy415/workspace/rainbow/tests/wave_optics_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;78;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_wave_optics_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_wave_optics_cpu_tests.exe")
  set_tests_properties([=[rainbow_wave_optics_cpu]=] PROPERTIES  LABELS "cpu;optics;focal;diffraction" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/wave_optics_tests.cmake;17;add_test;C:/Users/sy415/workspace/rainbow/tests/wave_optics_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;78;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_wave_optics_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_wave_optics_cpu_tests.exe")
  set_tests_properties([=[rainbow_wave_optics_cpu]=] PROPERTIES  LABELS "cpu;optics;focal;diffraction" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/wave_optics_tests.cmake;17;add_test;C:/Users/sy415/workspace/rainbow/tests/wave_optics_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;78;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_wave_optics_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_wave_optics_cpu_tests.exe")
  set_tests_properties([=[rainbow_wave_optics_cpu]=] PROPERTIES  LABELS "cpu;optics;focal;diffraction" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/wave_optics_tests.cmake;17;add_test;C:/Users/sy415/workspace/rainbow/tests/wave_optics_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;78;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_wave_optics_cpu]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_wave_optics_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_wave_optics_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/Debug/patch_optics.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/Debug/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/Debug/patch_query.optixir")
  set_tests_properties([=[rainbow_wave_optics_cuda]=] PROPERTIES  LABELS "gpu;cuda;optix;optics;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/wave_optics_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/wave_optics_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;78;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_wave_optics_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_wave_optics_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/Release/patch_optics.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/Release/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/Release/patch_query.optixir")
  set_tests_properties([=[rainbow_wave_optics_cuda]=] PROPERTIES  LABELS "gpu;cuda;optix;optics;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/wave_optics_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/wave_optics_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;78;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_wave_optics_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_wave_optics_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/MinSizeRel/patch_optics.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/MinSizeRel/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/MinSizeRel/patch_query.optixir")
  set_tests_properties([=[rainbow_wave_optics_cuda]=] PROPERTIES  LABELS "gpu;cuda;optix;optics;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/wave_optics_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/wave_optics_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;78;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_wave_optics_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_wave_optics_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/RelWithDebInfo/patch_optics.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/RelWithDebInfo/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/RelWithDebInfo/patch_query.optixir")
  set_tests_properties([=[rainbow_wave_optics_cuda]=] PROPERTIES  LABELS "gpu;cuda;optix;optics;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/wave_optics_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/wave_optics_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;78;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_wave_optics_cuda]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_patch_failure_report_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_patch_failure_report_cpu_tests.exe")
  set_tests_properties([=[rainbow_patch_failure_report_cpu]=] PROPERTIES  LABELS "cpu;diagnostics;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_failure_report_tests.cmake;15;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_failure_report_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;79;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_patch_failure_report_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_patch_failure_report_cpu_tests.exe")
  set_tests_properties([=[rainbow_patch_failure_report_cpu]=] PROPERTIES  LABELS "cpu;diagnostics;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_failure_report_tests.cmake;15;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_failure_report_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;79;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_patch_failure_report_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_patch_failure_report_cpu_tests.exe")
  set_tests_properties([=[rainbow_patch_failure_report_cpu]=] PROPERTIES  LABELS "cpu;diagnostics;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_failure_report_tests.cmake;15;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_failure_report_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;79;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_patch_failure_report_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_patch_failure_report_cpu_tests.exe")
  set_tests_properties([=[rainbow_patch_failure_report_cpu]=] PROPERTIES  LABELS "cpu;diagnostics;numerics" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_failure_report_tests.cmake;15;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_failure_report_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;79;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_patch_failure_report_cpu]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_patch_failure_capture_gpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_patch_failure_capture_gpu_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_raindrop_trace_module.dir/Debug/raindrop_trace.optixir" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/Debug/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/Debug/patch_query.optixir" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/Debug/patch_optics.fatbin")
  set_tests_properties([=[rainbow_patch_failure_capture_gpu]=] PROPERTIES  LABELS "gpu;cuda;optix;diagnostics;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_failure_report_tests.cmake;26;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_failure_report_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;79;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_patch_failure_capture_gpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_patch_failure_capture_gpu_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_raindrop_trace_module.dir/Release/raindrop_trace.optixir" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/Release/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/Release/patch_query.optixir" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/Release/patch_optics.fatbin")
  set_tests_properties([=[rainbow_patch_failure_capture_gpu]=] PROPERTIES  LABELS "gpu;cuda;optix;diagnostics;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_failure_report_tests.cmake;26;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_failure_report_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;79;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_patch_failure_capture_gpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_patch_failure_capture_gpu_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_raindrop_trace_module.dir/MinSizeRel/raindrop_trace.optixir" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/MinSizeRel/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/MinSizeRel/patch_query.optixir" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/MinSizeRel/patch_optics.fatbin")
  set_tests_properties([=[rainbow_patch_failure_capture_gpu]=] PROPERTIES  LABELS "gpu;cuda;optix;diagnostics;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_failure_report_tests.cmake;26;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_failure_report_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;79;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_patch_failure_capture_gpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_patch_failure_capture_gpu_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_raindrop_trace_module.dir/RelWithDebInfo/raindrop_trace.optixir" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/RelWithDebInfo/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/RelWithDebInfo/patch_query.optixir" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/RelWithDebInfo/patch_optics.fatbin")
  set_tests_properties([=[rainbow_patch_failure_capture_gpu]=] PROPERTIES  LABELS "gpu;cuda;optix;diagnostics;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/patch_failure_report_tests.cmake;26;add_test;C:/Users/sy415/workspace/rainbow/tests/patch_failure_report_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;79;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_patch_failure_capture_gpu]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_folded_patch_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_folded_patch_cpu_tests.exe")
  set_tests_properties([=[rainbow_folded_patch_cpu]=] PROPERTIES  LABELS "cpu;optics;folded;regression" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/folded_patch_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/folded_patch_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;80;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_folded_patch_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_folded_patch_cpu_tests.exe")
  set_tests_properties([=[rainbow_folded_patch_cpu]=] PROPERTIES  LABELS "cpu;optics;folded;regression" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/folded_patch_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/folded_patch_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;80;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_folded_patch_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_folded_patch_cpu_tests.exe")
  set_tests_properties([=[rainbow_folded_patch_cpu]=] PROPERTIES  LABELS "cpu;optics;folded;regression" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/folded_patch_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/folded_patch_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;80;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_folded_patch_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_folded_patch_cpu_tests.exe")
  set_tests_properties([=[rainbow_folded_patch_cpu]=] PROPERTIES  LABELS "cpu;optics;folded;regression" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/folded_patch_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/folded_patch_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;80;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_folded_patch_cpu]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_folded_patch_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_folded_patch_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/Debug/patch_optics.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/Debug/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/Debug/patch_query.optixir")
  set_tests_properties([=[rainbow_folded_patch_cuda]=] PROPERTIES  LABELS "gpu;cuda;optix;optics;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/folded_patch_tests.cmake;19;add_test;C:/Users/sy415/workspace/rainbow/tests/folded_patch_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;80;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_folded_patch_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_folded_patch_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/Release/patch_optics.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/Release/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/Release/patch_query.optixir")
  set_tests_properties([=[rainbow_folded_patch_cuda]=] PROPERTIES  LABELS "gpu;cuda;optix;optics;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/folded_patch_tests.cmake;19;add_test;C:/Users/sy415/workspace/rainbow/tests/folded_patch_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;80;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_folded_patch_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_folded_patch_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/MinSizeRel/patch_optics.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/MinSizeRel/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/MinSizeRel/patch_query.optixir")
  set_tests_properties([=[rainbow_folded_patch_cuda]=] PROPERTIES  LABELS "gpu;cuda;optix;optics;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/folded_patch_tests.cmake;19;add_test;C:/Users/sy415/workspace/rainbow/tests/folded_patch_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;80;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_folded_patch_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_folded_patch_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/RelWithDebInfo/patch_optics.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/RelWithDebInfo/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/RelWithDebInfo/patch_query.optixir")
  set_tests_properties([=[rainbow_folded_patch_cuda]=] PROPERTIES  LABELS "gpu;cuda;optix;optics;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/folded_patch_tests.cmake;19;add_test;C:/Users/sy415/workspace/rainbow/tests/folded_patch_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;80;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_folded_patch_cuda]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_unpolarized_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_unpolarized_cpu_tests.exe")
  set_tests_properties([=[rainbow_unpolarized_cpu]=] PROPERTIES  LABELS "cpu;optics;unpolarized;regression" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/unpolarized_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/unpolarized_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;81;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_unpolarized_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_unpolarized_cpu_tests.exe")
  set_tests_properties([=[rainbow_unpolarized_cpu]=] PROPERTIES  LABELS "cpu;optics;unpolarized;regression" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/unpolarized_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/unpolarized_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;81;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_unpolarized_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_unpolarized_cpu_tests.exe")
  set_tests_properties([=[rainbow_unpolarized_cpu]=] PROPERTIES  LABELS "cpu;optics;unpolarized;regression" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/unpolarized_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/unpolarized_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;81;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_unpolarized_cpu]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_unpolarized_cpu_tests.exe")
  set_tests_properties([=[rainbow_unpolarized_cpu]=] PROPERTIES  LABELS "cpu;optics;unpolarized;regression" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/unpolarized_tests.cmake;18;add_test;C:/Users/sy415/workspace/rainbow/tests/unpolarized_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;81;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_unpolarized_cpu]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rainbow_unpolarized_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Debug/rainbow_unpolarized_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_raindrop_trace_module.dir/Debug/raindrop_trace.optixir" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/Debug/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/Debug/patch_query.optixir" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/Debug/patch_optics.fatbin")
  set_tests_properties([=[rainbow_unpolarized_cuda]=] PROPERTIES  LABELS "gpu;cuda;optix;unpolarized;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/unpolarized_tests.cmake;19;add_test;C:/Users/sy415/workspace/rainbow/tests/unpolarized_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;81;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rainbow_unpolarized_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/Release/rainbow_unpolarized_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_raindrop_trace_module.dir/Release/raindrop_trace.optixir" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/Release/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/Release/patch_query.optixir" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/Release/patch_optics.fatbin")
  set_tests_properties([=[rainbow_unpolarized_cuda]=] PROPERTIES  LABELS "gpu;cuda;optix;unpolarized;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/unpolarized_tests.cmake;19;add_test;C:/Users/sy415/workspace/rainbow/tests/unpolarized_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;81;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rainbow_unpolarized_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/MinSizeRel/rainbow_unpolarized_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_raindrop_trace_module.dir/MinSizeRel/raindrop_trace.optixir" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/MinSizeRel/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/MinSizeRel/patch_query.optixir" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/MinSizeRel/patch_optics.fatbin")
  set_tests_properties([=[rainbow_unpolarized_cuda]=] PROPERTIES  LABELS "gpu;cuda;optix;unpolarized;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/unpolarized_tests.cmake;19;add_test;C:/Users/sy415/workspace/rainbow/tests/unpolarized_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;81;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rainbow_unpolarized_cuda]=] "C:/Users/sy415/workspace/rainbow/build-verify/tests/RelWithDebInfo/rainbow_unpolarized_cuda_tests.exe" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_raindrop_trace_module.dir/RelWithDebInfo/raindrop_trace.optixir" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_build_module.dir/RelWithDebInfo/patch_build.fatbin" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_query_module.dir/RelWithDebInfo/patch_query.optixir" "C:/Users/sy415/workspace/rainbow/build-verify/rainbow_patch_optics_module.dir/RelWithDebInfo/patch_optics.fatbin")
  set_tests_properties([=[rainbow_unpolarized_cuda]=] PROPERTIES  LABELS "gpu;cuda;optix;unpolarized;integration" _BACKTRACE_TRIPLES "C:/Users/sy415/workspace/rainbow/tests/unpolarized_tests.cmake;19;add_test;C:/Users/sy415/workspace/rainbow/tests/unpolarized_tests.cmake;0;;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;81;include;C:/Users/sy415/workspace/rainbow/tests/CMakeLists.txt;0;")
else()
  add_test([=[rainbow_unpolarized_cuda]=] NOT_AVAILABLE)
endif()
